version: "3.9" # optional since v1.27.0
services:
  cache:
    networks:
      - chat_system
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ~/docker-conf/redis/data/:/data
      - ./go_creationEndpoint/Server/RedisCache/redis.conf:/usr/local/etc/redis/redis.conf
  rabbitmq:
    image: rabbitmq:3-management-alpine
    # network_mode: "host"
    networks:
      - chat_system
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/docker-conf/rabbitmq/log/:/var/log/rabbitmq

networks:
  chat_system:
    driver: bridge